spring:
  application:
    name: SpringAIStarter

  config:
    import: optional:file:.env[.properties]
  
  data:
    redis:
      host: localhost
      port: 6379
      client-type: jedis

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  ai:
    model:
      chat: google-genai
      embedding:
        text: google-genai

    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3-flash-preview
        embedding:
          api-key: ${GEMINI_API_KEY}
          text:
            model: gemini-embedding-001

    vectorstore:
      redis:
        initialize-schema: true
        index-name: earning-reports
        prefix: earnings